"""empty message

Revision ID: 7b24b5da473b
Revises: b72dbff6121e
Create Date: 2026-02-26 21:04:01.319383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b24b5da473b'
down_revision: Union[str, Sequence[str], None] = 'b72dbff6121e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_searches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_search')
    op.add_column('devices', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('devices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('deleted_email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_email')
    op.drop_column('devices', 'updated_at')
    op.drop_column('devices', 'created_at')
    op.create_table('users_search',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('term', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_search_pkey'))
    )
    op.drop_table('user_sessions')
    op.drop_table('user_searches')
    # ### end Alembic commands ###
